# This is where YOU define your app. Edit this file.
# The builder.py will read this and turn it into a native Android project.

APP_CONFIG = {
    "app_name": "My First App",
    "package_name": "com.eugene.myfirstapp",
    "version_code": 1,
    "version_name": "1.0",
    
    # Theme colors
    "primary_color": "#6200EE",
    "primary_dark_color": "#3700B3",

    # List your screens. This is the part you will expand.
    "screens": [
        {
            "name": "Home",
            "activity_name": "MainActivity",
            "layout_name": "activity_main",
            "widgets": [
                {"type": "TextView", "id": "welcomeText", "text": "Hello from Python!"},
                {"type": "Button", "id": "actionButton", "text": "Click Me", "action": "showToast:Hello Eugene!"},
                {"type": "EditText", "id": "nameInput", "hint": "Enter your name"}
            ]
        },
        {
            "name": "About",
            "activity_name": "AboutActivity",
            "layout_name": "activity_about",
            "widgets": [
                {"type": "TextView", "id": "aboutText", "text": "This app was generated by a Python catalyst!"},
                {"type": "Button", "id": "backButton", "text": "Go Back", "action": "finish"}
            ]
        }
    ]
}
